### ISSUE TITLE
Missing template files in data

### ISSUE THREAD

**Issue by sian-chen** [Ber666/ToolkenGPT#10]
In [L37](https://github.com/Ber666/ToolkenGPT/blob/main/inference_modes.py#L37) of `inference_modes.py`:
```python
prompt = templates[op].replace("[QUESTION]", question) + cur_generation_with_func
```
It tries to get the template of a specific operation, which is loaded from `data/` by L97-L99 in `inference_llama.py`:
```python
for name in os.listdir("data/funcqa/template_oh"):
    with open(f"data/funcqa/template_oh/{name}") as f:
        templates[name.split("_")[-1].replace(".txt", "")] = f.read()
```
However, in the downloaded data directories `data/funcqa/template_oh` and `data/funcqa/template_mh`, there are only `llama_func.txt` and `llama_general.txt`. The lack of templates lead to `KeyError` during inference thus the generated sentences are not completed.

Could you please upload the missing template files so that we can run inference on GSM8K-XL and FuncQA?
Thanks!

**Comment by Leolty** [comment]
Sorry for the oversight. We should have double-checked the data. Please find the missing template files at the following link:

[Complete Data Link](https://drive.google.com/file/d/12iNW6i9YfZYBrp4pUxylXUNq0NiWGBEu/view?usp=sharing)

We appreciate your patience and feedback. I am updating the README accordingly to reflect this. Thank you for bringing this to our attention.

**Comment by Ber666** [comment]
Closed the issue for now. Feel free to reopen it if that doesn't solve your problem.
