### ISSUE TITLE
Incorrect FuncQA Multi-Hop Ground Truth

### ISSUE THREAD

**Issue by chenhongqiao** [Ber666/ToolkenGPT#11]
The answer for question 6 seems incorrect:
`
{
        "question": "Rectangular A has a length of 3.64 cm, its width is 1.23 cm shorter than the length, the area of the  A is ?",
        "answer": "8.7824",
        "calculation": [
            "<subtract>(3.64,1.23)=2.41",
            "<multiply>(2.41,3.64)=8.7824"
        ]
    }
`

2.41*3.64 should be 8.7724, not 8.7824. This can lead to correct responses being marked wrong given the 0.1% tolerance.

**Comment by Leolty** [comment]
Thank you for pointing this out, and you're absolutely right. I'm genuinely sorry for the oversight. We have corrected the mistake. We appreciate your feedback to ensure accuracy in our repo.
