### ISSUE TITLE
kamel inference code 

### ISSUE THREAD

**Issue by lisaalaz** [Ber666/ToolkenGPT#14]
Hi, 

Thank you for your great work on ToolkenGPT. I am trying to run the repo but it seems that the inference code for kamel is not generating the arguments or evaluating the results. 

Could you advise on how to do that? Many thanks!

**Comment by Ber666** [comment]
Hi, thanks for your interest in our work!

We found that argument prediction in this task is trivial for Llama-33B (always 100% accuracy in our exploratory experiments). Thus we skipped this step and only focused on the tool selection in this experiments, especially in the scenario where we have a large tool set.
