### ISSUE TITLE
ReAct in Table 2

### ISSUE THREAD

**Issue by siyuyuan** [Ber666/ToolkenGPT#16]
Sorry, my question has not been resolved yet I found that the previous issue was closed. Please don't be too quick to close :)

So, in Table 2, is ReAct used with llama? How did you operate it? Can you release your code? 
And if it's llama 30B (not llama 2), does it have the ability to follow instructions? I tried the 30B llama, and I found its ability to follow instructions is quite weak, so I'm wondering if it can perform react operations?"

**Comment by Ber666** [comment]
Yes, the results of ReAct are based on the same LLM of ToolkenGPT, Llama-33B.
The prompt of ReAct is listed in the appendix of our [paper](https://arxiv.org/pdf/2305.11554.pdf). Generally, to make it work, the prompt needs to contain a few demonstrations in addition to the instruction.
We will try to organize the code of ReAct, but that may take some time. Hopefully the information above is helpful. Feel free to follow up if there is still something unclear.

**Comment by siyuyuan** [comment]
> Yes, the results of ReAct are based on the same LLM of ToolkenGPT, Llama-33B. The prompt of ReAct is listed in the appendix of our [paper](https://arxiv.org/pdf/2305.11554.pdf). Generally, to make it work, the prompt needs to contain a few demonstrations in addition to the instruction. We will try to organize the code of ReAct, but that may take some time. Hopefully the information above can already help you reproduce the results.

Thanks!

**Comment by Ber666** [comment]
Close the issue for now. Feel free to re-open it if you have any questions later.

**Comment by siyuyuan** [comment]
Hi, I tried to implement chatgpt+react and vicuna+react using the methods in sections A.2.3 and A.2.4 of your paper, but I am confused about how exactly you do this. Your paper mentions: 

> 'ReAct incorporates special syntax to call operators, e.g., "... The cost is 50*3.2=<multiply>(50,3.2)=160". Once the syntax is detected during inference, the tool would be called to calculate the result.' 

However, in the paper ReAct: Synergizing Reasoning and Acting in Language Models, the authors said they do react by action+thought as follows:

> Question What is the elevation range for the area that the eastern sector of the Colorado orogeny extends into? 
> Thought 1 I need to search Colorado orogeny, find the area that the eastern sector of the Colorado orogeny extends into, then find the elevation range of the area. 
> Action 1 Search[Colorado orogeny] 
> Observation 1 The Colorado orogeny was an episode of mountain building (an orogeny) in Colorado and surrounding areas.

So, how is this implemented using chatgpt and vicuna if i used your prompt as the method you mentioned in your paper? Can you share your llama 30B+react code?
