### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jvhoffbauer** [Ber666/ToolkenGPT#21]
Under which license is the code and especially the dataset distributed?

**Comment by Ber666** [comment]
Hi, the datasets after our modifications follow the same licenses of the original datasets, i.e., MIT License for [GSM8k](https://github.com/openai/grade-school-math/blob/master/LICENSE), and The Creative Commons Attribution-Noncommercial 4.0 International License for [KAMEL](https://huggingface.co/datasets/LeandraFichtel/KAMEL).

Other original datasets and the code are distributed with Apache 2.0

**Comment by jvhoffbauer** [comment]
Thanks @Ber666
