### ISSUE TITLE
Can you provide the numerical ACC result on Kamel in Figure 2 of the paper?

### ISSUE THREAD

**Issue by fairyshine** [Ber666/ToolkenGPT#23]
Especially for ICL, ICL(desc) and Prompting.
Or if you could provide the code for it. Thank you!

**Comment by Ber666** [comment]
Hi, I just uploaded a jupyter notebook. Let me know if you have any other questions.

**Comment by fairyshine** [comment]
Awesome！
That‘s all. Thank you for the help again!

By the way, the script of training funqa in README may miss the parameter "--dataset funcqa". I add it by myself otherwise there might be some error.
