### ISSUE TITLE
questions about training data

### ISSUE THREAD

**Issue by ftgreat** [Ber666/ToolkenGPT#4]
The paper refers two mode in Figure1: reasoning mode and tool mode.
I think the paired data is used for training in reasoning mode. 
Do we need other data for tool mode, for example, samples for <toolken> argument completions? 
Or how is the paired data used for training in tool mode?

Thanks for your reply.

**Comment by Ber666** [comment]
Hi, thanks for your interest. Tool mode works with in-context learning. There are a few ReACT-style demonstrations in the prompt. No paired data is needed.
