### ISSUE TITLE
About dataset `FuncQA`

### ISSUE THREAD

**Issue by yc1999** [Ber666/ToolkenGPT#5]
since `FuncQA` is a synthetic dataset, have you manually checked the correctness of the test dataset ?
<img width="287" alt="image" src="https://github.com/Ber666/ToolkenGPT/assets/37548571/3a540356-e0e5-4b8b-a1b8-79763ceb4a4b">

**Comment by Ber666** [comment]
@Leolty Could you answer the question?

**Comment by Leolty** [comment]
@yc1999 I've basically checked everything, but as you may notice some questions are kind of convoluted, plus I might sometimes be a bit careless (especially after reviewing too many of these convoluted questions). If you find any issues, please make sure to bring them up!
