### ISSUE TITLE
Can you share the trained models?

### ISSUE THREAD

**Issue by yonatanbitton** [Ber666/ToolkenGPT#6]
Hi and thanks for the great work. 
I want to run your models on inference. Can you share the trained models checkpoint so I can run the inference commands?
Thank you.

**Comment by Ber666** [comment]
Hi, thanks for your interest in our work, and sorry for the late reply.

The checkpoints for kamel and virtualhome are [here](https://drive.google.com/file/d/1hHBpy1Oqc1xEd2iQAtSlyi1KCtNFBzIn/view?usp=sharing), while my coauthors will update the checkpoints for math datasets later. 

At the same time, we'll be happy to assist you if there are any difficulties in the process of training.

**Comment by Leolty** [comment]
Hi, sorry for the late.

The checkpoints for gsm8k and funcqa can be downloaded [here](https://drive.google.com/drive/folders/18rE11en3pkB0lA_WObaD_09G7FtwS8lP?usp=sharing).
