### ISSUE TITLE
Missing KAMEL templates

### ISSUE THREAD

**Issue by chenhongqiao** [Ber666/ToolkenGPT#7]
Data missing KAMEL templates

**Comment by Ber666** [comment]
Thanks for letting me know this. The data link has been updated.

**Comment by chenhongqiao** [comment]
<img width="743" alt="CleanShot 2023-09-04 at 11 49 40@2x" src="https://github.com/Ber666/ToolkenGPT/assets/30813603/671b71ef-ee22-487a-8b27-128aec8828d9">

Apparently the link is private?

**Comment by Ber666** [comment]
Fixed
