### ISSUE TITLE
Evaluation code for FuncQA

### ISSUE THREAD

**Issue by sian-chen** [Ber666/ToolkenGPT#8]
The current inference script for FuncQA only generates the first tool to use.
It do not generate the arguments and the consequence inference for multi-hop tool-using.
Could you please provide the complete evaluation code to reproduce the results in the paper?
Thanks!

**Comment by Ber666** [comment]
Hi, thanks for your feedback. It should be fixed now. Feel free to re-open the issue if there are still any problems.

**Comment by sian-chen** [comment]
Thanks for the quick response!
Another problem is that the inference results are not completed.

The command in the README run `inference_llama_for_math.py` to inference for FuncQA, but the file doesn't exist so I replaced `inference_llama_for_math.py` with `inference_llama.py`.

The following is the results of FuncQA:

>{"case_idx": 0, "question": "A car depreciates by 11% each year. In 8 years, what is the value of the car of its original price? (in decimal form)", "func_calls": [], "generation": "The car depreciates by 11% each year. In 8 years, the value of the car is 0.89^8=<power>(", "status": "'<power>'"}

The outputs are stopped at the function call without the arguments so they cannot be evaluated.

Could you provide the missing `inference_llama_for_math.py` or the correct command to run inference?

Thanks.

**Comment by Leolty** [comment]
Hello,

Thank you for pointing this out.

1. You're correct in observing the discrepancy. The README should have used `inference_llama.py`. It seems that there's a typo in the documentation. We apologize for the oversight.

2. As for the incomplete output, everything is functioning correctly on our end with `inference_llama.py`. Have you ensured that you've checked out the most recent commit of the repository?

**Comment by sian-chen** [comment]
The problem seems due to the lack of template files. Please refer to this issue #10.
